### PR TITLE
docs: Advice user to activate plugin

### PR DESCRIPTION
**Pull request by georgkrause**
Its obvious, still something you better do to make it work ;)

### CODE REVIEW

**Comment by georgkrause** [comment]
Well, if you started using Pelican before 4.5 you might have a `PLUGIN` in your `pelicanconf.py`, which results in the autodetection to not work. However, I agree we can adjust the addition a bit to make it clearer its only needed if this key is already present.

**Comment by georgkrause** [comment]
Additionally, there seem to be legacy plugins, that are not installable, in this scenario I have to use the `PLUGINS` configuration, and if I specify it for one, the auto detection for others isn't working anymore

**Comment by justinmayer** [comment]
Related to above-linked issue no. 3131, I just added the following commit, which could be used as a model for how to handle this on an individual plugin level: https://github.com/pelican-plugins/more-categories/commit/586effaafed5ad6ec0747623dea9536d6536f558

**Comment by georgkrause** [comment]
@justinmayer Just to make this clear here: none of my previous comments were meant as a attack. I just had issues and wanted to avoid the same for others.

However, I agree there is no point in duplicating this. Your linked template even seems verbose to me and its surely sufficient. I'll close my MR in favour of your solution

**Comment by justinmayer** [comment]
@georgkrause: To be clear, I did not perceive any attack. The time I can spend on open source is limited, so I often have to be more succinct than I would prefer. 😊

**Pull request closed without merging**
